''' Excel Spreadsheet '''
TEAM_HOME = 2
TEAM_AWAY = 3
FT_GOALS_HOME = 4
FT_GOALS_AWAY = 5
FT_RESULT = 6
HT_GOALS_HOME = 7
HT_GOALS_AWAY = 8
HT_RESULT = 9
SHOTS_HOME = 11
SHOTS_AWAY = 12
SHOTS_TARGET_HOME = 13
SHOTS_TARGET_AWAY = 14
FOULS_HOME = 15
FOULS_AWAY = 16
CORNERS_HOME = 17
CORNERS_AWAY = 18
YELLOWS_HOME = 19
YELLOWS_AWAY = 20
REDS_HOME = 21
REDS_AWAY = 22

''' Fixture Data '''
# HOME_ID, ...
#    HOME_AVG_GOALS, HOME_L1_GOALS, HOME_L5_GOALS, HOME_L10_GOALS, HOME_SEASON_GOALS, ...
#    HOME_AVG_SHOTS_ON, HOME_L1_SHOTS_ON, HOME_L5_SHOTS_ON, HOME_L10_SHOTS_ON, HOME_SEASON_SHOTS_ON, ...
#    HOME_AVG_SHOTS_OFF, HOME_L1_SHOTS_OFF, HOME_L5_SHOTS_OFF, HOME_L10_SHOTS_OFFFF, HOME_SEASON_SHOTS_OFF, ...
#    HOME_AVG_CORNERS, HOME_L1_CORNERS, HOME_L5_CORNERS, HOME_L10_CORNERS, HOME_SEASON_CORNERS, ...
#    HOME_AVG_FOULS, HOME_L1_FOULS, HOME_L5_FOULS, HOME_L10_FOULS, HOME_SEASON_FOULS, ...
#    HOME_AVG_YELLOWS, HOME_L1_YELLOWS, HOME_L5_YELLOWS, HOME_L10_YELLOWS, HOME_SEASON_YELLOWS, ...
#    HOME_AVG_REDS, HOME_L1_REDS, HOME_L5_REDS, HOME_L10_REDS, HOME_SEASON_REDS, ...

HOME_ID = 0

HOME_AVG_GOALS = 1
HOME_L1_GOALS = 2
HOME_L5_GOALS = 3
HOME_L10_GOALS = 4
HOME_SEASON_GOALS = 5

HOME_AVG_SHOTS_ON = 6
HOME_L1_SHOTS_ON = 7
HOME_L5_SHOTS_ON = 8
HOME_L10_SHOTS_ON = 9
HOME_SEASON_SHOTS_ON = 10

HOME_AVG_SHOTS_OFF = 11
HOME_L1_SHOTS_OFF = 12
HOME_L5_SHOTS_OFF = 13
HOME_L10_SHOTS_OFF = 14
HOME_SEASON_SHOTS_OFF = 15

HOME_AVG_CORNERS = 16
HOME_L1_CORNERS = 17
HOME_L5_CORNERS = 18
HOME_L10_CORNERS = 19
HOME_SEASON_CORNERS = 20

HOME_AVG_FOULS = 21
HOME_L1_FOULS = 22
HOME_L5_FOULS = 23
HOME_L10_FOULS = 24
HOME_SEASON_FOULS = 25

HOME_AVG_YELLOWS = 26
HOME_L1_YELLOWS = 27
HOME_L5_YELLOWS = 28
HOME_L10_YELLOWS = 29
HOME_SEASON_YELLOWS = 30

HOME_AVG_REDS = 31
HOME_L1_REDS = 32
HOME_L5_REDS = 33
HOME_L10_REDS = 34
HOME_SEASON_REDS = 35
