''' Excel Spreadsheet '''
TEAM_HOME = 2
TEAM_AWAY = 3
FT_GOALS_HOME = 4
FT_GOALS_AWAY = 5
FT_RESULT = 6
HT_GOALS_HOME = 7
HT_GOALS_AWAY = 8
HT_RESULT = 9
SHOTS_HOME = 11
SHOTS_AWAY = 12
SHOTS_TARGET_HOME = 13
SHOTS_TARGET_AWAY = 14
FOULS_HOME = 15
FOULS_AWAY = 16
CORNERS_HOME = 17
CORNERS_AWAY = 18
YELLOWS_HOME = 19
YELLOWS_AWAY = 20
REDS_HOME = 21
REDS_AWAY = 22

''' Fixture Data '''
# ID, ...
#    AVG_GOALS, L1_GOALS, L5_GOALS, L10_GOALS, SEASON_GOALS, ...
#    AVG_GOALS_HT, L1_GOALS_HT, L5_GOALS_HT, L10_GOALS_HT, SEASON_GOALS_HT, ...
#    AVG_SHOTS_ON, L1_SHOTS_ON, L5_SHOTS_ON, L10_SHOTS_ON, SEASON_SHOTS_ON, ...
#    AVG_SHOTS_OFF, L1_SHOTS_OFF, L5_SHOTS_OFF, L10_SHOTS_OFF, SEASON_SHOTS_OFF, ...
#    AVG_CORNERS, L1_CORNERS, L5_CORNERS, L10_CORNERS, SEASON_CORNERS, ...
#    AVG_FOULS, L1_FOULS, L5_FOULS, L10_FOULS, SEASON_FOULS, ...
#    AVG_YELLOWS, L1_YELLOWS, L5_YELLOWS, L10_YELLOWS, SEASON_YELLOWS, ...
#    AVG_REDS, L1_REDS, L5_REDS, L10_REDS, SEASON_REDS, ...
#    AVG_GOALS_HT_AGAINST, L1_GOALS_HT_AGAINST, L5_GOALS_HT_AGAINST, L10_GOALS_HT_AGAINST, SEASON_GOALS_HT_AGAINST, ...
#    AVG_GOALS_AGAINST, L1_GOALS_AGAINST, L5_GOALS_AGAINST, L10_GOALS_AGAINST, SEASON_GOALS_AGAINST, ...
#    AVG_SHOTS_ON_AGAINST, L1_SHOTS_ON_AGAINST, L5_SHOTS_ON_AGAINST, L10_SHOTS_ON_AGAINST, SEASON_SHOTS_ON_AGAINST, ...
#    AVG_SHOTS_OFF_AGAINST, L1_SHOTS_OFF_AGAINST, L5_SHOTS_OFF_AGAINST, L10_SHOTS_OFF_AGAINST, SEASON_SHOTS_OFF_AGAINST, ...
#    AVG_CORNERS_AGAINST, L1_CORNERS_AGAINST, L5_CORNERS_AGAINST, L10_CORNERS_AGAINST, SEASON_CORNERS_AGAINST, ...
#    AVG_FOULS_AGAINST, L1_FOULS_AGAINST, L5_FOULS_AGAINST, L10_FOULS_AGAINST, SEASON_FOULS_AGAINST, ...
#    AVG_YELLOWS_AGAINST, L1_YELLOWS_AGAINST, L5_YELLOWS_AGAINST, L10_YELLOWS_AGAINST, SEASON_YELLOWS_AGAINST, ...
#    AVG_REDS_AGAINST, L1_REDS_AGAINST, L5_REDS_AGAINST, L10_REDS_AGAINST, SEASON_REDS_AGAINST, ...
#    AVG_FORM, L1_FORM, L5_FORM, L10_FORM, SEASON_FORM, ...
#    PERCENTAGE_WIN, PERCENTAGE_LOSE, PERCENTAGE_TIE, ...
#    HOME, GAME_ID

ID = 0

AVG_GOALS = 1
L1_GOALS = 2
L5_GOALS = 3
L10_GOALS = 4
SEASON_GOALS = 5

AVG_GOALS_HT = 6
L1_GOALS_HT = 7
L5_GOALS_HT = 8
L10_GOALS_HT = 9
SEASON_GOALS_HT = 10

AVG_SHOTS_ON = 11
L1_SHOTS_ON = 12
L5_SHOTS_ON = 13
L10_SHOTS_ON = 14
SEASON_SHOTS_ON = 15

AVG_SHOTS_OFF = 16
L1_SHOTS_OFF = 17
L5_SHOTS_OFF = 18
L10_SHOTS_OFF = 19
SEASON_SHOTS_OFF = 20

AVG_CORNERS = 21
L1_CORNERS = 22
L5_CORNERS = 23
L10_CORNERS = 24
SEASON_CORNERS = 25

AVG_FOULS = 26
L1_FOULS = 27
L5_FOULS = 28
L10_FOULS = 29
SEASON_FOULS = 30

AVG_YELLOWS = 31
L1_YELLOWS = 32
L5_YELLOWS = 33
L10_YELLOWS = 34
SEASON_YELLOWS = 35

AVG_REDS = 36
L1_REDS = 37
L5_REDS = 38
L10_REDS = 39
SEASON_REDS = 40

AVG_GOALS_AGAINST = 41
L1_GOALS_AGAINST = 42
L5_GOALS_AGAINST = 43
L10_GOALS_AGAINST = 44
SEASON_GOALS_AGAINST = 45

AVG_GOALS_HT_AGAINST = 46
L1_GOALS_HT_AGAINST = 47
L5_GOALS_HT_AGAINST = 48
L10_GOALS_HT_AGAINST = 49
SEASON_GOALS_HT_AGAINST = 50

AVG_SHOTS_ON_AGAINST = 51
L1_SHOTS_ON_AGAINST = 52
L5_SHOTS_ON_AGAINST = 53
L10_SHOTS_ON_AGAINST = 54
SEASON_SHOTS_ON_AGAINST = 55

AVG_SHOTS_OFF_AGAINST = 56
L1_SHOTS_OFF_AGAINST = 57
L5_SHOTS_OFF_AGAINST = 58
L10_SHOTS_OFF_AGAINST = 59
SEASON_SHOTS_OFF_AGAINST = 60

AVG_CORNERS_AGAINST = 61
L1_CORNERS_AGAINST = 62
L5_CORNERS_AGAINST = 63
L10_CORNERS_AGAINST = 64
SEASON_CORNERS_AGAINST = 65

AVG_FOULS_AGAINST = 66
L1_FOULS_AGAINST = 67
L5_FOULS_AGAINST = 68
L10_FOULS_AGAINST = 69
SEASON_FOULS_AGAINST = 70

AVG_YELLOWS_AGAINST = 71
L1_YELLOWS_AGAINST = 72
L5_YELLOWS_AGAINST = 73
L10_YELLOWS_AGAINST = 74
SEASON_YELLOWS_AGAINST = 75

AVG_REDS_AGAINST = 76
L1_REDS_AGAINST = 77
L5_REDS_AGAINST = 78
L10_REDS_AGAINST = 79
SEASON_REDS_AGAINST = 80

AVG_FORM = 81
L1_FORM = 82
L5_FORM = 83
L10_FORM = 84
SEASON_FORM = 85

TOTAL_WIN = 86
TOTAL_TIE = 87
TOTAL_LOSE = 88
PERCENTAGE_WIN = 89
PERCENTAGE_TIE = 90
PERCENTAGE_LOSE = 91

HOME = 92
GAME_ID = 93
